export const FETCH_WAREHOUSES = 'FETCH_WAREHOUSES';
export const UPDATE_WAREHOUSE = 'UPDATE_WAREHOUSE';
export const DELETE_WAREHOUSE = 'DELETE_WAREHOUSE';
export const ADD_WAREHOUSE = 'ADD_WAREHOUSE';